### ISSUE TITLE
Is this project maintained actively?

### ISSUE THREAD

**Issue by shon** [epicserve/s3-backups#15]
s3-backups is nice handy tool. Thanks for creating it. 

I see couple of worthy pull requests with no response. So I wonder if it is actively maintained?

**Comment by epicserve** [comment]
I just haven't had time. :) I looked at one of the pull request but couldn't duplicate the error. I need to figure out easier ways of running tests.

**Comment by shon** [comment]
@epicserve thanks for quick response :)

pull#7 and pull#14 looks fine to me. pull#9 looks like major refactoring so may be can wait but 7 and 14 IMO should be accepted. Can I help?

Cheers.

**Comment by epicserve** [comment]
FYI, I pulled in PR #7 and I've made some comments on PR #14.

**Comment by shon** [comment]
Many thanks @epicserve. I agree with your comments on #14. Makes sense.
