### ISSUE TITLE
Issue in Redis Backup Script

### ISSUE THREAD

**Issue by sandeephello** [epicserve/s3-backups#17]
I am not able to see the logic in script to take backup of Redis.

Defiantly some modifications are required. 

Regards
Sandeep Sharma

**Comment by epicserve** [comment]
Can you be more specific? I'm not sure I understand what you're talking about. Are you saying the [documentation](http://s3-backups.readthedocs.org/en/latest/#redis) doesn't make sense? Or it isn't working? Please be specific.

**Comment by sandeephello** [comment]
I am talking about Redis script i.e. https://github.com/epicserve/s3-backups/blob/master/s3_backups/redis_to_s3.py

There is no code to take the backup of AWS Redis. How are you taking the backup of Redis?

**Comment by epicserve** [comment]
Yeah, this tool is for backing up your own Redis server to S3, it's not for backing up ElastiCache/Redis on AWS. I would assume that Amazon has their own tools for backing up Redis.
